### ISSUE TITLE
Typo in description of 'getjumps' command

### ISSUE THREAD

**Issue by AftershockMedia** [SleepyFugu/avorioncontrol#1]
The description embed of this command states a maximum of 25 jumps can be retrieved; I've been informed that this is no longer up to date and needs changing.

![image](https://user-images.githubusercontent.com/74832349/99883864-e99f3480-2c21-11eb-9655-e267bb96d48e.png)

**Comment by SleepyFugu** [comment]
Corrected in commit: https://github.com/SleepyFugu/avorioncontrol/commit/4a120c7348cf9efbfaa6ea4872eb7daf3c882395
