### ISSUE TITLE
!!help command returning differently ordered lists each time it's run

### ISSUE THREAD

**Issue by AftershockMedia** [SleepyFugu/avorioncontrol#2]
Each time the !!help command is run, the commands will be listed in a different order to the previously returned list. Reminder from convo earlier - "The answer is that they are stored in a hash which is unordered."

![image](https://user-images.githubusercontent.com/74832349/99884437-2c630b80-2c26-11eb-9110-e852c2b9bb47.png)

**Comment by SleepyFugu** [comment]
Fixed in commit https://github.com/SleepyFugu/avorioncontrol/commit/7a39ae8a66742d18720629c84f27d39ee3b9cfb6
